export enum Actions {
    UPDATE_DATE = 'UPDATE_DATE',
    UPDATE_PEOPLE = 'UPDATE_PEOPLE',
    UPDATE_NAME = 'UPDATE_NAME',
    UPDATE_LASTNAME = 'UPDATE_LASTNAME',
    UPDATE_EXP_ID = 'UPDATE_EXP_ID',
    RESET = 'RESET',
  }